### Submit Orders
POST http://localhost:4004/browse/Orders
Content-Type: application/json

{ "OrderNo":"2019-09...", "Items":[
    { "book_ID":207, "amount":5 }
]}

# Sending this three times should result in a 409: 5 exceeds stock for book #201

### Check books entity that stock was reduced
GET http://localhost:4004/admin/Books(207)

###
POST http://localhost:4004/admin/Books
Content-Type: application/json

{
    "ID" : 199,
    "title" : "Fitness Kochbuch",
    "author_ID" : 10,
    "stock" : 100

}

###
POST http://localhost:4004/admin/Authors
Content-Type: application/json

{
    "ID" : 10,
    "name" : "Chirs C"
}